# .theme-check.yml
extends:
  - theme-check:recommended

# Ignore paths you don’t want scanned
ignore:
  - node_modules/**
  - dist/**
  - assets/*.map

# Turn off noisy rules globally (optional)
InlineStyles:
  enabled: false

InlineJavaScript:
  enabled: false
