name: CI
on: [push, pull_request]

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: '.'          # adjust if your theme is in a subfolder
          token: ${{ github.token }} # enables inline annotations
          base: main               # optional, nice for PRs
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install theme-check (Ruby CLI)
        run: gem install theme-check
      - name: Generate JSON report (don’t fail this step)
        run: theme-check --no-color --format json > theme-check-report.json || true
      - name: Upload Theme Check report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: theme-check-report
          path: theme-check-report.json

